name: PMCJoinTravel
version: ${project.version}
main: com.popupmc.jointravel.JoinTravel
description: ${project.description}
author: junebug12851
api-version: 1.15

commands:
  joinTravel:
    aliases: [jt]
    description: Join Travel Continue
    usage: Command was not registered properly.
