name: JoinTravel
version: 1.0
main: com.popupmc.jointravel.JoinTravel
description: Join Travel
author: junebug12851
api-version: 1.15

commands:
  jt-continue:
    permission: jt.continue
    permission-message: You don't have permission to perform this action
    description: Join Travel Continue
    usage: /jt-continue <player>
